spring.application.name=livestock-farming
server.port=8281
spring.datasource.url=jdbc:postgresql://localhost:5432/livestock-farming
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ========== JWT Configuration ==========
jwt.signerKey=BpbYzjZCyoHbx8E8AvSPDFxsE0739IlW4YKWheQPHSnIDtl/3jZNcLiKonRqda2DQ1rr72U0EUZ0TksWFBLBzwaS
jwt.valid-duration=1800
# 15 phut
jwt.refreshable-duration=360000
# 1 gio

# ========== Cookie Configuration ==========
# LOCALHOST
cookie.domain=
cookie.secure=false
cookie.same-site=Lax

# PRODUCTION (Uncomment khi deploy)
#cookie.domain=yourdomain.com
#cookie.secure=true
#cookie.same-site=Strict

cookie.path=/
cookie.name=refreshToken